# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Breeze', '0006_auto_20180110_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='registration',
            name='registration_id',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
