# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Breeze', '0007_auto_20180110_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='payable',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
